# Generated by Django 5.0.6 on 2024-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('assigned_to', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
